SELECT NAME, POSITION AS 직위, 2026-YEAR_EMP 재직연수
FROM PROFESSOR

SELECT * 
FROM STUDENT S1, STUDENT S2

SELECT S2.NAME
FROM STUDENT S1, STUDENT S2
WHERE S1.ADDRESS = S2.ADDRESS
AND S1.NAME = '김광식'

SELECT *
FROM STUDENT 
WHERE ADDRESS ='서울'

SELECT ADDRESS
FROM STUDENT 
WHERE NAME='김광식'

SELECT S.NAME, D.DEPT_NAME
FROM  STUDENT s, DEPARTMENT D
WHERE S.DEPT_ID = D.DEPT_ID

SELECT NAME, STU_ID
FROM STUDENT 
WHERE YEAR = 3 OR YEAR = 4
ORDER BY NAME DESC, STU_ID

SELECT STUDENT.STU_ID, STUDENT.DEPT_ID
FROM STUDENT, DEPARTMENT
WHERE STUDENT.DEPT_ID =DEPARTMENT.DEPT_ID 
AND STUDENT.YEAR = 3 
AND DEPARTMENT.DEPT_NAME='컴퓨터공학과'

SELECT NAME, DEPT_NAME
FROM STUDENT, DEPARTMENT
WHERE STUDENT.DEPT_ID =DEPARTMENT.DEPT_ID

SELECT * FROM STUDENT

SELECT * FROM DEPARTMENT


SELECT STUDENT.NAME, STUDENT.STU_ID, DEPARTMENT.DEPT_NAME
FROM STUDENT, DEPARTMENT
WHERE STUDENT.DEPT_ID =DEPARTMENT.DEPT_ID

SELECT DEPT_ID, DEPT_NAME
FROM DEPARTMENT

SELECT NAME, STU_ID, DEPT_ID
FROM STUDENT

SELECT NAME, 2026-YEAR_EMP
FROM PROFESSOR

SELECT RESIDENT_ID, STU_ID, NAME, YEAR
FROM STUDENT

SELECT DISTINCT ADDRESS
FROM STUDENT

SELECT * FROM STUDENT 

INSERT INTO STUDENT 
VALUES ('1292002', '900305*1730021', '강승진', 3, '서울', '921')

DELETE --SELECT * 
FROM PROFESSOR
WHERE NAME ='김태석'

SELECT * FROM PROFESSOR

SELECT *
FROM STUDENT
WHERE NAME LIKE '김%'

SELECT *
FROM STUDENT 
WHERE RESIDENT_ID LIKE '%*2%'
OR RESIDENT_ID LIKE '%*4%'

SELECT * FROM EMP

SELECT NAME FROM STUDENT 
UNION ALL
SELECT NAME FROM PROFESSOR

SELECT S.STU_ID
FROM STUDENT S, DEPARTMENT D, TAKES T
WHERE S.DEPT_ID = D.DEPT_ID 
AND T.STU_ID = S.STU_ID 
AND DEPT_NAME = '컴퓨터공학과'
AND GRADE = 'A+'

SELECT STU_ID  --[1292001], 1292002, [1292003]
FROM STUDENT S, DEPARTMENT D
WHERE S.DEPT_ID = D.DEPT_ID 
AND DEPT_NAME = '컴퓨터공학과'
INTERSECT
SELECT STU_ID  --[1292001], [1292003], 1292303
FROM TAKES 
WHERE GRADE = 'A+'

SELECT STU_ID 
FROM STUDENT S, DEPARTMENT D -- 129301, [1292303], 1292305
WHERE S.DEPT_ID = D.DEPT_ID 
AND DEPT_NAME = '산업공학과'
MINUS
SELECT STU_ID 
FROM TAKES 
WHERE GRADE = 'A+' --1292001, 1292003, [1292303]

SELECT * FROM COURSE 

SELECT * FROM CLASS

SELECT TITLE, CREDIT, YEAR, SEMESTER, DIVISION
FROM COURSE, CLASS
WHERE COURSE.COURSE_ID = CLASS.COURSE_ID 








